
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/caicloud/clientset"
  branch = "release-1.14"

[[constraint]]
  name = "github.com/evanphx/json-patch"
  branch = "master"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/golang/glog"
  branch = "master"

[[constraint]]
  name = "k8s.io/helm"
  branch = "pkg"
  source = "github.com/caicloud/helm"

[[constraint]]
  name = "github.com/buger/jsonparser"
  branch = "master"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "=v1.14.2"

[[override]]
  name = "golang.org/x/oauth2"
  revision = "a6bd8cefa1811bd24b86f8902872e4e8225f74c4"

[[override]]
  name = "golang.org/x/net"
  revision = "1c05540f6879653db88113bc4a2b70aec4bd491f"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.14.2"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.14.2"

[[constraint]]
  name = "github.com/caicloud/go-common"
  version = "=v0.1.4"

[prune]
  go-tests = true
  unused-packages = true
